from .antibodies import AntibodiesEndpoint
from .attachments import AttachmentsEndpoint
from .bacteria import BacteriaEndpoint
from .biocollections import BiocollectionsEndpoint
from .boxes import BoxesEndpoint
from .cell_lines import CellLinesEndpoint
from .comments import CommentsEndpoint
from .companies import CompaniesEndpoint
from .compounds import CompoundsEndpoint
from .datasets import DatasetsEndpoint
from .documents import DocumentsEndpoint
from .experiments import ExperimentsEndpoint
from .flies import FliesEndpoint
from .folders import FoldersEndpoint
from .fungi import FungiEndpoint
from .genes import GenesEndpoint
from .lipids import LipidsEndpoint
from .plants import PlantsEndpoint
from .projects import ProjectsEndpoint
from .proteins import ProteinsEndpoint
from .protocols import ProtocolsEndpoint
from .sections import SectionsEndpoint
from .reports import ReportsEndpoint
from .sequences import SequencesEndpoint
from .sessions import SessionsEndpoint
from .shopping_list import ShoppingListEndpoint
from .sops import SopsEndpoint
from .stocks import StocksEndpoint
from .storages import StoragesEndpoint
from .tags import TagsEndpoint
from .teams import TeamsEndpoint
from .tissues import TissuesEndpoint
from .units import UnitsEndpoint
from .vectors import VectorsEndpoint
from .viruses import VirusesEndpoint
from .visualizations import VisualizationsEndpoint
from .webhooks import WebhooksEndpoint
from .worms import WormsEndpoint
from .yeasts import YeastsEndpoint
