name: pytest

on:
  workflow_dispatch:
  push: 
    branches: [main]

jobs: 
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install pip --upgrade
          pip install -r requirements-dev.txt --upgrade
            
      - name: Test
        run: python -m pytest tests/